### ISSUE TITLE
FreeBitco.in?

### ISSUE THREAD

**Issue by bgiesing** [skorulis/beermoney-balances#2]
The balance is at the top right corner of every page so should be easy to add the number. The problem would be you would also have to add a BTC to USD API to get the USD value like you do for every other site.

https://freebitco.in/

**Comment by skorulis** [comment]
Added in 282a01ac50e42c1c26e5d843a4937a7b34bf9333. Will take a few hours for the store version to update. Because the script only runs when a page loads and it's an SPA you will have to refresh to get the balance to update. 

In regards to conversion I'm just using a static conversion for now. I'm doing the same thing for UK pounds to USD. It's not ideal but for the values people are likely to have it will suffice.

As an aside, are sites like that worth it? You can only make about 5c a day and have to waste time solving captchas.

**Comment by bgiesing** [comment]
@skorulis Well they recently added a rewards point system which you can keep exponentially increasing.

For instance, you can get 4 RP/roll by going to settings and disabling the Lotto tickets. Then buy the 1 extra per roll for 12 RP (they all last 24 hours). 3 rolls and you already made that up and since you can only have one at a time, you can get alot till the 24 hours end. Then you do the 10 RP/roll for 120 RP, 50 RP/roll for 600 RP, and then 100 RP/roll for 1,200 RP. In a few days you can get to the 100RP/roll and quickly get enough for at least 3-4 100 RP/roll redeems.

Keep farming the RP till you have enough of a stash to do multiple days of 1000% bonus on the Free Rolls.

Even if it isn't much, the Google ReCaptcha is just one click on the checkbox every hour, takes 2 seconds.

**Comment by skorulis** [comment]
Interesting method. I'll give it a bit more of a go. Have you found any other decent bitcoin faucets?

**Comment by bgiesing** [comment]
@skorulis Not really, all the good ones basically shut down because Google's mass revoking of AdSense. BitMaker is good but it's mobile only so not handy for this.
